import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState,useEffect, createContext} from 'react'
import {useRouter} from'next/router'
import {Button,Form,Loader} from 'semantic-ui-react'
import Link from 'next/link'
export default function Home() {
  const [form,setForm] = useState({name:'',email:'',phone:'',number:''})
  const[isSubmitting,setIsSubmitting]=useState(false)
  const [errors,setErrors]=useState({})
  const router = useRouter()
  
  useEffect(() => {
      if(isSubmitting){
        if(Object.keys(errors).length === 0){
          createNote();
          alert('Show this certification to staff')
        }
        else{
          setIsSubmitting(false)
        }
      }
  },[errors])
  const createNote = async()=>{
    try{
      const res = await fetch('https://botton-copy.vercel.app/api/hh',{
        method:'POST',
        headers:{
          "Accept":"application/json",
          "Content-Type":"application/json"
        },
        body:JSON.stringify(form)
      })
      router.push("/")
    }catch(error){
      console.log(error)
    }
  }

  const handleSubmit = (e)=>{
    e.preventDefault()
    let errs = validate();
    setErrors(errs)
    setIsSubmitting(true)
  }

  const handleChange = (e)=>{
    setForm({
      ...form,
        [e.target.name]:e.target.value
    })
  }
  const validate = ()=>{
    let err = {}
    if(!form.name){
      err.name='Name is required'
    }
    if(!form.email){
      err.email='Email is required'
    }
    if(!form.phone){
      err.phone='Phone is required'
    }
    if(!form.number){
      err.number='Number is required'
    }
    return err
  }
  return (
    <div className="form-group">
      <Head>
        <title>Fill up list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="form-container">
        <h1>Create Note</h1>
        <div>
            {isSubmitting ? <Loader active inline='centered'/>
                            :<Form onSubmit={handleSubmit}>
                              <Form.Input 
                                fluid
                                label='name'
                                name='name'
                                placeholder="Ex:Ms.Lee"
                                error={errors.name?{ content:'Please enter a title',pointing:'below'}:null}
                                id="err-name"
                                onChange={handleChange}
                                />
                                 <Form.Input 
                                fluid
                                error={errors.email?{content:'Enter a email',pointing:'below'}:null}
                                label='email'
                                id="err-email"
                                name='email'
                                type='email'
                                placeholder={errors.email}
                                onChange={handleChange}
                                />
                                 <Form.Input 
                                fluid
                                id="err-phone"
                                error={errors.phone?{content:'Enter a phone',pointing:'below'}:null}
                                label='phone'
                                name='phone'
                                placeholder={errors.phone}

                                onChange={handleChange}
                                />
                                 <Form.Input 
                                fluid
                                error={errors.number?{content:'Enter a number',pointing:'below'}:null}
                                label='number'
                                id="err-number"
                                name='number'
                                placeholder={errors.number}
                                onChange={handleChange}
                                />
                                <Button type="submit">Submit</Button>
                            </Form>
          }
        
        </div>
        <footer>CopyRight&&Hung</footer>
      </div>
     
      
    </div>
  )
}
